twig:
    default_path: '%kernel.project_dir%/templates'

    #globals:
    #    batman: "Batman"
    #    gproducts: '@App\Globals\Products'
    #    gbrand: '@App\Globals\Brands'
    #    gtypes: '@App\Globals\Types'

    # on déclare le theme à utiliser pour les formulaires de notre site
    
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true


